services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.php  # Utiliser le Dockerfile personnalisé
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony 
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    platform: linux/arm64
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
