controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_movie:
    path: /add-movie
    controller: App\Controller\MovieController::addMovie
